# Generated by Django 4.0.6 on 2022-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0002_article_tags_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tags.tag', verbose_name='Теги'),
        ),
    ]
